version: "3.8"

services:
  tg-connector:
    image: peteranikitin/telegads-tg-connector:latest
    pull_policy: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "3003:80"
    networks:
      - tg_connector_network
    volumes:
      - ./sessions:/code/sessions
      - ./bad_sessions:/code/bad_sessions

networks:
  tg_connector_network:
    driver: bridge
    name: tg_connector_network_stage
