version: "3.8"

services:
  tg-connector:
    image: peteranikitin/tg-connector-prod:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "3003:80"
    networks:
      - network
    volumes:
      - ./sessions:/app/sessions
      - ./bad_sessions:/app/bad_sessions

networks:
  network:
    driver: overlay
