apiVersion: v1
kind: PersistentVolume 
metadata:
  name: tg-connector-{{ .Values.env }}-sessions
  labels:
    type: local 
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.capacity.storage }} 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tg-connector/data/session
---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: tg-connector-{{ .Values.env }}-bad-sessions
  labels:
    type: local 
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.capacity.storage }} 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tg-connector/data/bad_sessions
