name: deploy-to-production

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy staging stack to swarm
        uses: appleboy/ssh-action@master
        with:
          host: telegads.uz
          username: ci
          password: ${{ secrets.SSH_CI_PASS }}
          script: docker compose -f /tg-connector-stage/docker-compose.yml -f /tg-connector-stage/docker-compose.prod.yml up -d
