name: deploy-to-staging

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-tg-connector:latest
          file: ./deploy/Dockerfile

      - name: Build and push staging image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-tg-connector-stage:latest
          file: ./deploy/Dockerfile-deploy
          build-args: |
            TG_APP_ID_ARG=${{secrets.TG_APP_ID_STAGE}}
            TG_APP_HASH_ARG=${{secrets.TG_APP_HASH_STAGE}}

      - name: Build and push production image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-tg-connector-prod:latest
          file: ./deploy/Dockerfile-deploy
          build-args: |
            TG_APP_ID_ARG=${{secrets.TG_APP_ID_PROD}}
            TG_APP_HASH_ARG=${{secrets.TG_APP_HASH_PROD}}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy staging
        uses: appleboy/ssh-action@master
        with:
          host: telegads.uz
          username: ci
          password: ${{ secrets.SSH_CI_PASS }}
          script: docker compose -f /tg-connector-stage/docker-compose.yml -f /tg-connector-stage/docker-compose.stage.yml up  --force-recreate --build -d
