name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-tg-connector:latest
          file: ./deploy/Dockerfile
          build-args: |
            TG_API_ID_ARG=${{secrets.TG_APP_ID_STAGE}}
            TG_API_HASH_ARG=${{secrets.TG_APP_HASH_STAGE}}
            S3_ACCESS_ID_ARG=${{secrets.S3_ACCESS_ID}}
            S3_ACCESS_KEY_ARG=${{secrets.S3_ACCESS_KEY}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy staging
        uses: appleboy/ssh-action@master
        with:
          host: telegads.uz
          username: ci
          password: ${{ secrets.SSH_CI_PASS }}
          script: docker compose -f /tg-connector/docker-compose.yml pull && docker compose -f /tg-connector/docker-compose.yml up  --force-recreate --build -d
