name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: peteranikitin/telegads-tg-connector:latest
          file: ./deploy/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
      - name: set secrets
        uses: DamianReeves/write-file-action@master
        with:
          path: ./deploy/tg-connector/values/production/main.yaml
          contents: |
            TG_API_ID_ARG: ${{secrets.TG_APP_ID_STAGE}}
            TG_API_HASH_ARG: ${{secrets.TG_APP_HASH_STAGE}}
            S3_ACCESS_ID_ARG: ${{secrets.S3_ACCESS_ID}}
            S3_ACCESS_KEY_ARG: ${{secrets.S3_ACCESS_KEY}}
          write-mode: append

      - name: print values
        run: cat   ./deploy/tg-connector/values/production/main.yaml

      - name: apply staging
        run: |
          helmfile apply -f ./deploy/tg-connector/helmfile.yaml --environment production